### Obtener productos
GET http://localhost:80/products

### Crear producto
POST http://localhost:80/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjhkMDMwMDQxODIwNzdkMjZiNGNiZiIsImlhdCI6MTYzOTUwMTg3MiwiZXhwIjoxNjM5NTg4MjcyfQ.AnBBjscpwJ8Uk9aBM4Zg8MVZTXhq0hhcj4CkKz9CLGo

{   
    "name": "Ajiaco",
    "price": 20,
    "imagen": "no imagen",
    "type":"almuerzo",
    "dateEntry": "2021-12-14"
}

### Obtener un solo producto 
GET http://localhost:80/products/61a90cd45ed2cce78aa602eb
### Editar producto
PUT http://localhost:80/products/61a691e729fc68bc2c9085ee
Content-Type: application/json

{
    "name": "sandwich de pollo",
    "price": 5,
    "imagen": "sandwich",
    "type": "lunch"   
}

### Borrar producto
DELETE http://localhost:80/products/61a90cc55ed2cce78aa602e9